# THIS IS THE CONFIGURATION USED BY PODS TO NETWORK INTERNALLY WITHIN THE CLUSTER 
model_db:
  pool_size: 1
  password: password
  user: root
  host: model-db-mysql
  port: 3306
  database: model_db

scheduler:
  cluster_mount_point: /dummy/dir

results_db:
  password:  password
  user: root
  host: results-db-mongodb
  port: 27017
